@extends('layouts.app', ['title' => 'إصدار شهادة'])
@section('content')
<div class="mb-8"><p class="mb-2 text-sm font-bold text-gold">تكريم جديد</p><h1 class="text-3xl font-bold text-emerald-950">إصدار شهادة شرف</h1><p class="mt-2 text-slate-500">اختر قالبًا وطالبًا ثم راجع الصورة قبل التنزيل.</p></div>
<form id="issue-form" method="POST" action="{{ route('certificates.store') }}" class="grid gap-6 xl:grid-cols-[300px_1fr]">@csrf<div class="space-y-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div><label for="template-select" class="mb-2 block text-sm font-bold">قالب الشهادة</label><select id="template-select" name="certificate_template_id" required class="w-full rounded-2xl border border-slate-200 bg-sand px-4 py-3">@foreach($templates as $template)<option value="{{ $template->id }}" data-background="{{ Storage::disk('public')->url($template->background_path) }}" data-width="{{ $template->width }}" data-height="{{ $template->height }}" data-json='@json($template->canvas_json)'>{{ $template->name }}</option>@endforeach</select></div><div><label for="student-select" class="mb-2 block text-sm font-bold">الطالب</label><select id="student-select" name="student_id" required class="w-full rounded-2xl border border-slate-200 bg-sand px-4 py-3">@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->name }}</option>@endforeach</select></div><div class="rounded-2xl bg-emerald-50 p-4 text-sm leading-7 text-emerald-900"><i class="bx bx-info-circle"></i> سيتم استبدال موضع اسم الطالب بالاسم المختار ثم حفظ الصورة النهائية.</div><input type="hidden" id="issue-image" name="image"><button id="issue-submit" class="flex w-full items-center justify-center gap-2 rounded-2xl bg-emerald-950 py-3.5 font-bold text-white">إصدار وتنزيل <i class="bx bx-download text-lg text-gold"></i></button></div><div class="overflow-auto rounded-3xl bg-slate-100 p-4"><div id="issue-canvas-wrap" class="mx-auto w-fit bg-white shadow-xl"><canvas id="issue-canvas"></canvas></div></div></form>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/5.3.1/fabric.min.js"></script>
<script>
const issueCanvas=new fabric.Canvas('issue-canvas');const templateSelect=document.getElementById('template-select');const studentSelect=document.getElementById('student-select');let currentTemplate=null;function loadCertificate(){const option=templateSelect.options[templateSelect.selectedIndex];currentTemplate=option;const width=Number(option.dataset.width),height=Number(option.dataset.height);issueCanvas.clear();issueCanvas.setDimensions({width,height});fabric.Image.fromURL(option.dataset.background,(background)=>{issueCanvas.setBackgroundImage(background,issueCanvas.renderAll.bind(issueCanvas));issueCanvas.loadFromJSON(JSON.parse(option.dataset.json),()=>{issueCanvas.setBackgroundImage(background,issueCanvas.renderAll.bind(issueCanvas));const name=issueCanvas.getObjects().find((object)=>object.data?.role==='student_name');if(name){name.set({text:studentSelect.options[studentSelect.selectedIndex].text});}issueCanvas.renderAll();});});}templateSelect.addEventListener('change',loadCertificate);studentSelect.addEventListener('change',()=>{const name=issueCanvas.getObjects().find((object)=>object.data?.role==='student_name');if(name){name.set({text:studentSelect.options[studentSelect.selectedIndex].text});issueCanvas.renderAll();}});document.getElementById('issue-form').addEventListener('submit',async(event)=>{event.preventDefault();const name=issueCanvas.getObjects().find((object)=>object.data?.role==='student_name');if(!name){Swal.fire({icon:'warning',title:'موضع اسم الطالب غير موجود',text:'اختر قالبًا يحتوي على موضع اسم الطالب.',confirmButtonText:'فهمت'});return;}document.getElementById('issue-submit').disabled=true;document.getElementById('issue-image').value=issueCanvas.toDataURL({format:'png',multiplier:1});try{const response=await fetch(event.target.action,{method:'POST',body:new FormData(event.target),headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'}});if(!response.ok)throw new Error('تعذر إصدار الشهادة.');const result=await response.json();Swal.fire({icon:'success',title:'تم إصدار الشهادة',text:'سيبدأ التنزيل الآن.',showConfirmButton:false,timer:1500}).then(()=>window.location=result.download_url);}catch(error){Swal.fire({icon:'error',title:'تعذر إصدار الشهادة',text:error.message,confirmButtonText:'إغلاق'});}finally{document.getElementById('issue-submit').disabled=false;}});loadCertificate();
</script>
@endsection
