@extends('layouts.app', ['title' => 'جلسة التسميع'])
@section('content')
<style>
    .mushaf-page{font-family:'Amiri',serif;background:#fffdf5;background-image:linear-gradient(#8f6b3912 1px,transparent 1px);background-size:100% 34px;touch-action:pan-y;perspective:1400px;transform-style:preserve-3d}
    .mushaf-page.page-turn-next{animation:page-turn-next .42s ease both;transform-origin:right center}
    .mushaf-page.page-turn-previous{animation:page-turn-previous .42s ease both;transform-origin:left center}
    @keyframes page-turn-next{0%{opacity:.45;transform:rotateY(14deg) translateX(2%)}100%{opacity:1;transform:rotateY(0) translateX(0)}}
    @keyframes page-turn-previous{0%{opacity:.45;transform:rotateY(-14deg) translateX(-2%)}100%{opacity:1;transform:rotateY(0) translateX(0)}}
    .mushaf-text{font-size:1.2rem;line-height:2.15;text-align:justify}
    .mushaf-ayah{display:inline;color:#062c26}
    .mushaf-ayah.is-last{background:#c99b4a33;border-radius:.5rem;box-shadow:0 0 0 2px #c99b4a66}
    @media(min-width:640px){.mushaf-text{font-size:1.5rem;line-height:2.35}}
</style>
<div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a href="{{ route('session.narrations', [$student, $qiraat]) }}" class="mb-3 inline-flex items-center gap-1 text-sm font-bold text-slate-500"><i class="bx bx-right-arrow-alt"></i> تغيير الرواية</a><h1 class="text-3xl font-bold text-emerald-950">جلسة تسميع {{ $student->name }}</h1><p class="mt-2 text-slate-500">{{ $qiraat->name }} · {{ $isPairedSession ? 'كلا الروايتان' : 'رواية ' . $narration->name }} · آخر آية مؤكدة: {{ $progress->global_ayah_number ? $progress->surah_name . '، الآية ' . $progress->ayah_number : 'لم يبدأ بعد' }}</p></div><form method="POST" action="{{ $isPairedSession ? route('session.finish-both', [$student, $qiraat]) : route('session.finish', $session) }}">@csrf<button class="inline-flex items-center gap-2 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 font-bold text-red-700"><i class="bx bx-stop-circle"></i> إنهاء الجلسة</button></form></div>
<div id="mushaf-shell" data-page-template="{{ route('session.mushaf.page', [$student, $narration, 'PAGE']) }}" data-page="{{ $page }}">
    <div class="mb-5 rounded-3xl border border-slate-200 bg-white p-3 shadow-sm"><div class="flex items-center justify-between gap-2"><button type="button" data-page-action="previous" class="inline-flex items-center gap-2 rounded-2xl px-3 py-3 font-bold text-emerald-900 hover:bg-emerald-50 sm:px-4"><i class="bx bx-chevron-right text-2xl"></i><span class="hidden sm:inline">الصفحة السابقة</span></button><div class="shrink-0 text-center"><div class="text-xs text-slate-400">صفحة المصحف</div><div id="page-number" class="text-xl font-bold text-emerald-950">{{ $page }} <span class="text-sm font-normal text-slate-400">من 604</span></div></div><button type="button" data-page-action="next" class="inline-flex items-center gap-2 rounded-2xl px-3 py-3 font-bold text-emerald-900 hover:bg-emerald-50 sm:px-4"><span class="hidden sm:inline">الصفحة التالية</span><i class="bx bx-chevron-left text-2xl"></i></button></div><label class="mt-3 flex items-center gap-3 border-t border-slate-100 pt-3 text-right"><span class="shrink-0 text-sm font-bold text-emerald-950">الانتقال إلى سورة</span><select id="surah-select" aria-label="الانتقال إلى سورة" class="min-w-0 flex-1 rounded-xl border border-slate-200 bg-sand px-3 py-2.5 text-sm font-bold text-emerald-950 focus:border-gold focus:outline-none focus:ring-2 focus:ring-gold/30">@foreach($surahs as $surah)<option value="{{ $surah['number'] }}" data-page="{{ $surah['page'] }}" @selected($surah['number'] === $currentSurahNumber)>{{ $surah['number'] }}. {{ $surah['name'] }}</option>@endforeach</select></label></div>
    @if($quranError)<div id="mushaf-error" class="rounded-3xl border border-amber-200 bg-amber-50 p-8 text-center"><i class="bx bx-cloud-off mb-3 text-4xl text-amber-600"></i><h2 class="text-xl font-bold text-amber-900">بيانات المصحف غير متاحة حاليًا</h2><p class="mx-auto mt-2 max-w-xl text-amber-800">{{ $quranError }}</p><button onclick="location.reload()" class="mt-5 rounded-2xl bg-amber-700 px-5 py-3 font-bold text-white">إعادة المحاولة</button></div>@else
    <div id="mushaf-page" class="mushaf-page mx-auto max-w-4xl rounded-[2rem] border-[10px] border-[#d9c49b] p-5 shadow-2xl shadow-emerald-950/10 sm:p-10"><div class="mb-8 flex items-center justify-between border-b border-[#b99b68]/40 pb-5 text-sm text-[#765b32]"><span>المصحف الشريف</span><span id="surah-names" class="font-bold">{{ collect($verses)->pluck('surah_name')->filter()->unique()->implode(' · ') }}</span><span>{{ $page }}</span></div><div id="mushaf-text" class="mushaf-text text-emerald-950">@foreach($verses as $verse)<span class="mushaf-ayah {{ $verse['global_ayah_number'] === (int) $progress->global_ayah_number ? 'is-last' : '' }}">{{ $verse['text'] }}<button type="button" class="ayah-trigger mx-1 inline-grid h-7 w-7 place-items-center rounded-full bg-emerald-950 align-middle font-sans text-xs font-bold text-white transition hover:bg-gold hover:text-emerald-950" data-surah="{{ $verse['surah_number'] }}" data-ayah="{{ $verse['ayah_number'] }}" data-global="{{ $verse['global_ayah_number'] }}" data-page="{{ $verse['page_number'] }}">{{ $verse['ayah_number'] }}</button></span> @endforeach</div><div class="mt-10 border-t border-[#b99b68]/40 pt-4 text-center text-sm text-[#765b32]">اضغط على رقم الآية لتأكيد التسميع · اسحب يمينًا أو يسارًا لتغيير الصفحة</div></div>
    @endif
</div>
<form id="confirm-form" method="POST" action="{{ $isPairedSession ? route('session.confirm-both', [$student, $qiraat]) : route('session.confirm', $session) }}" class="hidden">@csrf<input name="surah_number"><input name="ayah_number"><input name="global_ayah_number"><input name="page_number"></form>
<script>
    const mushafShell=document.getElementById('mushaf-shell');
    const mushafPage=document.getElementById('mushaf-page');
    const mushafText=document.getElementById('mushaf-text');
    const pageNumber=document.getElementById('page-number');
    const surahNames=document.getElementById('surah-names');
    const surahSelect=document.getElementById('surah-select');
    const surahStartPages=@json(config('quran.surah_start_pages'));
    const pageTemplate=mushafShell.dataset.pageTemplate;
    const progressGlobal={{ $progress->global_ayah_number }};
    const initialPage=Number(mushafShell.dataset.page);
    const resumeAtLastAyah=()=>mushafText?.querySelector('.is-last')?.scrollIntoView({block:'center',behavior:'instant'});
    if(!new URLSearchParams(location.search).has('page')) {
        document.fonts.ready.then(()=>requestAnimationFrame(resumeAtLastAyah));
    }
    const esc=(value)=>String(value??'').replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
    const renderAyahs=(ayahs)=>ayahs.map((ayah)=>`<span class="mushaf-ayah ${Number(ayah.global_ayah_number)===progressGlobal?'is-last':''}">${esc(ayah.text)}<button type="button" class="ayah-trigger mx-1 inline-grid h-7 w-7 place-items-center rounded-full bg-emerald-950 align-middle font-sans text-xs font-bold text-white transition hover:bg-gold hover:text-emerald-950" data-surah="${esc(ayah.surah_number)}" data-ayah="${esc(ayah.ayah_number)}" data-global="${esc(ayah.global_ayah_number)}" data-page="${esc(ayah.page_number)}">${esc(ayah.ayah_number)}</button></span>`).join(' ');
    const bindAyahButtons=()=>document.querySelectorAll('.ayah-trigger').forEach((button)=>button.addEventListener('click',()=>Swal.fire({title:'تأكيد التسميع',text:'هل تريد حفظ هذه الآية كتقدم جديد؟',icon:'question',showCancelButton:true,confirmButtonText:'تأكيد الحفظ',cancelButtonText:'إلغاء',reverseButtons:true}).then((result)=>{if(result.isConfirmed){const form=document.getElementById('confirm-form');form.querySelector('[name=surah_number]').value=button.dataset.surah;form.querySelector('[name=ayah_number]').value=button.dataset.ayah;form.querySelector('[name=global_ayah_number]').value=button.dataset.global;form.querySelector('[name=page_number]').value=button.dataset.page;form.submit();}})));
    const updateControls=(page,selectedSurah=null)=>{mushafShell.dataset.page=page;pageNumber.innerHTML=`${page} <span class="text-sm font-normal text-slate-400">من 604</span>`;const currentSurah=selectedSurah??Object.entries(surahStartPages).filter(([,startPage])=>Number(startPage)<=page).at(-1)?.[0]??'1';if(surahSelect)surahSelect.value=currentSurah;document.querySelector('[data-page-action="previous"]').disabled=page<=1;document.querySelector('[data-page-action="next"]').disabled=page>=604;document.querySelectorAll('[data-page-action]').forEach((button)=>button.classList.toggle('opacity-40',button.disabled));};
    const loadPage=async(page,changeHistory=true,direction='next',selectedSurah=null)=>{if(page<1||page>604)return; mushafPage?.classList.remove('page-turn-next','page-turn-previous');void mushafPage?.offsetWidth;mushafPage?.classList.add(direction==='next'?'page-turn-next':'page-turn-previous');mushafPage?.classList.add('opacity-50');try{const response=await fetch(pageTemplate.replace('PAGE',page),{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('تعذر تحميل الصفحة');const payload=await response.json();if(mushafText){mushafText.innerHTML=renderAyahs(payload.ayahs);surahNames.textContent=[...new Set(payload.ayahs.map((ayah)=>ayah.surah_name).filter(Boolean))].join(' · ');document.querySelector('#mushaf-page > div:first-child > span:last-child').textContent=payload.page;bindAyahButtons();}updateControls(payload.page,selectedSurah);if(changeHistory)history.pushState({page:payload.page},'',`?page=${payload.page}`);}catch(error){Swal.fire({toast:true,position:'top-start',icon:'error',title:error.message,showConfirmButton:false,timer:3000});}finally{mushafPage?.classList.remove('opacity-50');}};
    document.querySelector('[data-page-action="previous"]').addEventListener('click',()=>loadPage(Number(mushafShell.dataset.page)-1,true,'previous'));document.querySelector('[data-page-action="next"]').addEventListener('click',()=>loadPage(Number(mushafShell.dataset.page)+1,true,'next'));surahSelect?.addEventListener('change',()=>loadPage(Number(surahStartPages[surahSelect.value]),true,'next',surahSelect.value));bindAyahButtons();let touchStart=0;mushafPage?.addEventListener('touchstart',(event)=>touchStart=event.changedTouches[0].screenX,{passive:true});mushafPage?.addEventListener('touchend',(event)=>{const delta=event.changedTouches[0].screenX-touchStart;if(Math.abs(delta)>50){const direction=delta>0?'next':'previous';loadPage(Number(mushafShell.dataset.page)+(direction==='next'?1:-1),true,direction);}},{passive:true});window.addEventListener('popstate',()=>loadPage(Number(new URLSearchParams(location.search).get('page'))||initialPage,false,'next'));updateControls(Number(mushafShell.dataset.page));
</script>
@endsection
