@extends('layouts.app', ['title' => 'اختيار الرواية'])
@section('content')
<div class="mb-8"><a href="{{ route('session.readings', $student) }}" class="mb-4 inline-flex items-center gap-1 text-sm font-bold text-slate-500"><i class="bx bx-right-arrow-alt"></i> تغيير القراءة</a><p class="mb-2 text-sm font-bold text-gold">الخطوة الثالثة</p><h1 class="text-3xl font-bold text-emerald-950">اختر الرواية</h1><p class="mt-2 text-slate-500">{{ $qiraat->name }} · الطالب: <strong>{{ $student->name }}</strong></p></div>
<div class="grid gap-4 sm:grid-cols-2">@foreach($qiraat->narrations as $narration)@php
    $items=$attempts->get($narration->id,collect()); $active=$items->first(fn($a)=>!$a->completed_at); $completed=$items->whereNotNull('completed_at')->count();
@endphp<a href="{{ route('session.mushaf', [$student, $narration]) }}" class="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-gold hover:shadow-lg"><div class="mb-7 flex items-start justify-between"><div class="grid h-12 w-12 place-items-center rounded-2xl bg-emerald-100 text-2xl text-emerald-800"><i class="bx bx-book-reader"></i></div><i class="bx bx-left-arrow-alt text-2xl text-gold"></i></div><h2 class="text-2xl font-bold text-emerald-950">رواية {{ $narration->name }}</h2><p class="mt-3 font-bold text-gold">أتم هذه الرواية {{ $completed }} مرات</p><div class="mt-4 border-t border-slate-100 pt-4 text-sm">@if($active && $active->progress->global_ayah_number)<span class="font-bold text-emerald-800">المرة {{ $active->attempt_number }} · آخر آية: {{ $active->progress->surah_name }}، الآية {{ $active->progress->ayah_number }}</span>@else<span class="text-slate-500">جاهزة لبدء المرة {{ $completed + 1 }}</span>@endif</div></a>@endforeach</div>
@php
    $active=$qiraat->narrations->map(fn($n)=>$attempts->get($n->id,collect())->first(fn($a)=>!$a->completed_at));
    $paired=$active->filter()->isEmpty() || ($active->filter()->count()===2&&$active->pluck('attempt_number')->unique()->count()===1&&$active->pluck('progress.global_ayah_number')->unique()->count()===1);
@endphp
<div class="mt-4">@if($paired)<a href="{{ route('session.mushaf.both', [$student, $qiraat]) }}" class="inline-flex items-center gap-2 rounded-2xl bg-emerald-950 px-5 py-4 font-bold text-white"><i class="bx bx-book-open"></i> كلا الروايتان</a>@else<button disabled class="cursor-not-allowed rounded-2xl bg-slate-200 px-5 py-4 font-bold text-slate-500">كلا الروايتان</button>@endif</div>
@error('paired_readings')<p class="mt-2 font-bold text-red-700">{{ $message }}</p>@enderror
@if($completion=session('narration_completed'))<script>window.addEventListener('DOMContentLoaded',()=>Swal.fire({title:'مبارك! 🎉',text:`أتم الطالب ${@json($completion['narration'])} في المرة ${@json($completion['attempt_number'])}.`,icon:'success'}));</script>@endif
@endsection
