@extends('layouts.app', ['title' => 'اختيار الرواية'])
@section('content')
<div class="mb-8"><a href="{{ route('session.readings', $student) }}" class="mb-4 inline-flex items-center gap-1 text-sm font-bold text-slate-500"><i class="bx bx-right-arrow-alt"></i> تغيير القراءة</a><p class="mb-2 text-sm font-bold text-gold">الخطوة الثالثة</p><h1 class="text-3xl font-bold text-emerald-950">اختر الرواية</h1><p class="mt-2 text-slate-500">{{ $qiraat->name }} · الإمام {{ $qiraat->imam }} · الطالب: <strong class="text-emerald-900">{{ $student->name }}</strong></p></div>
<div class="grid gap-4 sm:grid-cols-2">@foreach($qiraat->narrations as $narration)@php($progress = $narration->progress->first())<a href="{{ route('session.mushaf', [$student, $narration]) }}" class="group rounded-3xl border p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg {{ $progress?->is_complete ? 'border-gold bg-gradient-to-br from-emerald-950 to-emerald-800 text-white shadow-emerald-950/20' : 'border-slate-200 bg-white hover:border-gold' }}"><div class="mb-7 flex items-start justify-between"><div class="grid h-12 w-12 place-items-center rounded-2xl text-2xl {{ $progress?->is_complete ? 'bg-gold text-emerald-950' : 'bg-emerald-100 text-emerald-800' }}"><i class="{{ $progress?->is_complete ? 'bx bx-check-circle' : 'bx bx-book-reader' }}"></i></div><i class="bx bx-left-arrow-alt text-2xl text-gold transition group-hover:-translate-x-1"></i></div><h2 class="text-2xl font-bold {{ $progress?->is_complete ? 'text-white' : 'text-emerald-950' }}">رواية {{ $narration->name }}</h2><div class="mt-6 border-t pt-4 text-sm {{ $progress?->is_complete ? 'border-white/15' : 'border-slate-100' }}">@if($progress?->is_complete)<span class="inline-flex items-center gap-2 font-bold text-gold"><i class="bx bx-check-circle text-lg"></i> أتم هذه الرواية</span>@elseif($progress && $progress->global_ayah_number > 0)<span class="font-bold text-emerald-800">آخر آية: {{ $progress->surah_name }}، الآية {{ $progress->ayah_number }}</span>@else<span class="text-slate-400">لم يبدأ التسميع بعد</span>@endif</div></a>@endforeach</div>
@php($pairedProgressIsEqual = $qiraat->narrations->count() === 2 && $qiraat->narrations->pluck('progress')->map(fn ($progress) => $progress->first()?->global_ayah_number ?? 0)->unique()->count() === 1)
<div class="mt-4">
    @if($pairedProgressIsEqual)
        <a href="{{ route('session.mushaf.both', [$student, $qiraat]) }}" class="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-emerald-950 px-5 py-4 text-lg font-bold text-white transition hover:bg-emerald-800 sm:w-auto"><i class="bx bx-book-open"></i> كلا الروايتان</a>
    @else
        <button type="button" disabled title="لا يمكن التسميع للروايتين معًا لأن تقدمهما مختلف" class="inline-flex w-full cursor-not-allowed items-center justify-center gap-2 rounded-2xl bg-slate-200 px-5 py-4 text-lg font-bold text-slate-500 sm:w-auto"><i class="bx bx-lock-alt"></i> كلا الروايتان</button>
    @endif
</div>
@error('paired_readings')<p class="mt-2 text-sm font-bold text-red-700">{{ $message }}</p>@enderror
@if($completion = session('narration_completed'))<script>window.addEventListener('DOMContentLoaded',()=>Swal.fire({title:'مبارك! 🎉',html:`أتم الطالب رواية <strong>{{ $completion['narration'] }}</strong> من <strong>{{ $completion['qiraat'] }}</strong>.${@json($completion['qiraat_complete']) ? '<br><strong>وأتم الروايتين كاملتين!</strong>' : ''}`,icon:'success',confirmButtonText:'رائع',confirmButtonColor:'#062c26'}));</script>@endif
@endsection
